name: NuGet packages

# ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master
      - nuget-packages
    # paths:
    #   - src/WildStrategies.DocumentFramework/**


env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  MAYORNUMBER: 1
  MINORNUMBER: 0
  BUILDNUMBER: $GITHUB_RUN_ID
  PROJECT_PATH: src/WildStrategies.DocumentFramework



jobs:
  build-nuget:
    name: Build and publish nuget package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Nuget restor
        run: dotnet restore
      - name: Pack
        run: |
          dotnet pack --configuration=release \
            --include-symbols \
            --include-source \
            -o ./artifacts \
            -p:MayorNumber=${MAYORNUMBER:=1} \
            -p:MinorNumber=${MINORNUMBER:=0} \
            -p:BuildNumber=${BUILDNUMBER:=0} \
            -p:RevisionNumber=${REVISIONNUMBER:=0} \
            $PROJECT_PATH
      - name: Configure dotnet source
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
            <configuration>
                <packageSources>
                    <add key=\"github\" value=\"https://nuget.pkg.github.com/a3nick/index.json\" />
                </packageSources>
                <github>
                    <add key=\"Username\" value=\"a3nick\" />
                    <add key=\"ClearTextPassword\" value=\"${{ secrets.GITHUB_TOKEN }}\" />
                </github>
            </configuration>" > nuget.config
      - name: Publish
        run: |
          for package in ./artifacts/*.nupkg; do dotnet nuget push --source github $package; done