name: NuGet - Json Support

on:
  push:
    branches:
      - master
      - nuget-packages
    paths:
      - src/WildStrategies.DocumentFramework.Json/**


env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  MAYORNUMBER: 1
  MINORNUMBER: 0
  PROJECT_PATH: src/WildStrategies.DocumentFramework.Json



jobs:
  build-nuget:
    name: Build and publish nuget package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'
          source-url: https://nuget.pkg.github.com/a3nick/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Nuget restore
        run: dotnet restore
      - name: Pack
        run: |
          dotnet pack --configuration=release \
            --include-symbols \
            --include-source \
            -o ./artifacts \
            -p:MayorNumber=${MAYORNUMBER:=1} \
            -p:MinorNumber=${MINORNUMBER:=0} \
            -p:BuildNumber=${GITHUB_RUN_NUMBER:=0} \
            -p:RevisionNumber=${REVISIONNUMBER:=0} \
            $PROJECT_PATH
      - name: Publish
        run: |
          rm -f ./artifacts/*.symbols.nupkg
          for package in ./artifacts/*.nupkg; do dotnet nuget push $package; done