name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1


jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: '5.0'
      - name: Test
        env:
          DOTNET_CONNECTIONSTRINGS__MONGODB: mongodb://localhost:27017
          DOTNET_SETTINGS__DATABASENAME: test
          DOTNET_SETTINGS__RESTAURANTSCOLLECTIONNAME: test
        run: |
          dotnet restore &&
          dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\..\.artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --collect:"XPlat Code Coverage" --settings coverlet.runsettings.xml &&
          mkdir ./.artifacts -p &&
          for cover in $(find ./tests -type f -name 'coverage.*.xml'); do coverPath=${cover#./tests/};cp $cover ./.artifacts/${coverPath%%/*}-$(basename $cover); done &&
          sed 's|'"$(pwd)"'|.|g' -i .artifacts/*.xml