name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Test
        run: |
          dotnet restore &&
          dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --collect:"XPlat Code Coverage" --settings coverlet.runsettings.xml &&
          mkdir ./artifacts -p &&
          for cover in $(find ./tests -type f -name 'coverage.*.xml'); do coverPath=${cover#./tests/};cp $cover ./artifacts/${coverPath%%/*}-$(basename $cover); done &&
          sed 's|'"$(pwd)"'|.|g' -i artifacts/*.xml